# Generated by Django 5.2.8 on 2026-01-12 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('imagine', models.ImageField(upload_to='locatii/')),
                ('descriere', models.TextField()),
                ('categorie', models.CharField(choices=[('food', 'Food'), ('art', 'Art'), ('selfcare', 'Selfcare')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARTravel.locatie')),
            ],
            options={
                'unique_together': {('user', 'locatie')},
            },
        ),
    ]
